function update_from_url_by_class(cClass, cURL)
{		

	/*
	update_from_url_by_class
	Damon Vaughn Caskey
	2013-04-07
	
	Replace content of elements with class matching parameter with content generated by URL.
	
	cClass: Class to search for in elements.
	cURL: URL to get new content from.	
	*/
	
	var elems 	= "";	//Element array.
	var	i		= 0;	//Counter.

	elems = document.getElementsByTagName('*'), i;

	/*
	Get window object.
	*/
	if (window.XMLHttpRequest)
	{	//IE7+, Firefox, Chrome, Opera, Safari.
		xmlhttp=new XMLHttpRequest();
	}
	else
	{	//IE6, IE5.
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}
	
	/* Target div element to be recoded from PHP echo.	*/
	xmlhttp.onreadystatechange=function()
	{
		if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{
			/* Loop element collection and target any that have matching strings in their class tags. */
			for (i in elems) 
			{
				if((' ' + elems[i].className + ' ').indexOf(' ' + cClass + ' ') > -1) 
				{
					elems[i].innerHTML = xmlhttp.responseText;
				}
			}
		}
	}
	
	/* Get new content and apply to element(s). */
	xmlhttp.open("GET", cURL, true);
	xmlhttp.send();
}