<?php require_once($_SERVER['DOCUMENT_ROOT']."/libraries/php/classes/config.php"); //Basic configuration file. ?>

<!DOCtype html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "//www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="//www.w3.org/1999/xhtml">
<head>
<title>UK - Environmental Management</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.css">
<link rel="stylesheet" href="../libraries/css/style.css" type="text/css" />

<?php 
	$cLRoot		= $cDocroot."env/";
?>
</head>

<body>

<div id="container">
	<div id="mainNavigation">
		<?php include("../libraries/includes/inc_mainnav.php"); ?>
	</div>
	<div id="subContainer">
		<?php include($cLRoot."a_banner.php"); ?>
		<div id="subNavigation">
			<?php include("a_subnav.php"); ?>	
		</div>
		<div id="content">
			<h1><strong>Environmental Quality Management Center</strong></h1>
<p> The $2.4 million, 11,000-square-foot    Environmental Quality Management Center (EQMC) opened in March of 1998. This    convenient, centralized facility houses the university's Environmental Management    (EM) operations. It has approximately 1,000 square feet of office space and    10,000 square feet of waste storage area.</p>
            <p> EM is charged with handling all of the hazardous waste generated by the campus,    associated farms, and research centers in strict compliance with all federal,    state and local environmental regulations. EM provides waste pick up service    and brings the waste to the EQMC for processing. The various operations performed    at the EQMC include: unloading, segregating and bulking waste, </p>
          <ul>
              <li>analyzing unknown chemicals,</li>
              <li>treating certain wastes to render them nontoxic,</li>
              <li>recycling good chemicals to campus users,</li>
              <li>recycling fluorescent light bulbs and all types of batteries, and</li>
              <li>preparing and shipping waste to approved off-campus disposal sites.</li>
            </ul>
In <u>2009</u>, EM staff processed approximately <u>130,000</u> pounds of  waste at the EQMC. EM personel also assisted off campus generators in managing an additional <u>10,000</u> pounds of waste for disposal. The facility plays an integral   role in university's Waste Minimization Program, including our reuse,   recycling, bulking, and treatment activities.  Since its opening, we   have reduced the amount of waste shipped off site by more than half.
<p> Numerous engineering controls were incorporated into the design of the facility      enabling it to operate safely with no impact on the surrounding environment.      Floors and walls are 12-inch thick reinforced concrete. Floors are sealed and      sloped toward the center of the facility to keep liquids from migrating to      the exterior. The facility has sophisticated fire and vapor monitoring systems      and several fire suppression systems, all designed to quickly mitigate any      releases. The waste area is kept locked at all times to prevent unauthorized      entry. There are motion detectors and intrusion alarms throughout. All systems      are continuously monitored. EM is on call to respond to emergencies 24 hours      a day, 7 days a week.</p>
<p> Exhaust from the waste storage section and the chemical fume hoods is routed        through an elaborate ventilation system to induced-draft fans on top of        the Garrigus building adjacent to the EQMC. The air changes an average        of 6 times per hour and can be increased to 14 changes per hour if necessary.</p>
<p> The staff performs daily, weekly, and monthly safety inspections of the   operating areas and systems.  The EQMC is inspected periodically by   federal and state EPA personnel who review our operations and disposal   records to verify compliance with regulations.  In   conclusion, the EQMC is a state-of-the-art waste management facility   that has received high marks from our college and university peers. </p>
 The facility is located         at 355 Cooper Drive and is open from 8 a.m. to 5 p.m. Monday through Friday         year round, except for holidays. Please feel free to stop by for a visit.         Ask us any questions you might have about facility operations or our waste         minimization activities. Tours can be arranged for individuals or groups         on very short notice.</div>
	</div>
	<div id="sidePanel">
		<img src="../media/image/0102.jpg" /><br />
		<?php include("a_sidepanel.php"); ?>
	</div>
	<div id="footer">
		<?php include("../libraries/includes/inc_footer.php"); ?>
		
	</div>
</div>

<div id="footerPad">
<?php include("../libraries/includes/inc_footerpad.php"); ?>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40196994-1', 'uky.edu');
  ga('send', 'pageview');

</script>
</body>
</html>